# https://wiki.metacubex.one/example/#meta

######### é”šç‚¹ start #######
# proxy ç›¸å…³
use-pg:
  &use-pg {
    type: select,
    proxies:
      [
        é»˜è®¤,
        é€‰æ‹©æœºåœº,
        é¦™æ¸¯,
        å°æ¹¾,
        æ—¥æœ¬,
        æ–°åŠ å¡,
        ç¾å›½,
        å…¶å®ƒåœ°åŒº,
        æ‰‹åŠ¨é€‰æ‹©,
        æ‰‹åŠ¨é€‰æ‹©2,
        è‡ªåŠ¨é€‰æ‹©,
        è´Ÿè½½å‡è¡¡,
        æ•…éšœè½¬ç§»,
        DIRECT,
      ],
  }

# proxy ç›¸å…³ cn
use-pg-cn:
  &use-pg-cn {
    type: select,
    proxies:
      [
        DIRECT,
        é»˜è®¤,
        é€‰æ‹©æœºåœº,
        é¦™æ¸¯,
        å°æ¹¾,
        æ—¥æœ¬,
        æ–°åŠ å¡,
        ç¾å›½,
        å…¶å®ƒåœ°åŒº,
        æ‰‹åŠ¨é€‰æ‹©,
        æ‰‹åŠ¨é€‰æ‹©2,
        è‡ªåŠ¨é€‰æ‹©,
        è´Ÿè½½å‡è¡¡,
        æ•…éšœè½¬ç§»,
      ],
  }

#è¿™é‡Œæ˜¯è®¢é˜…æ›´æ–°å’Œå»¶è¿Ÿæµ‹è¯•ç›¸å…³çš„
use-health-check: &use-health-check {
    type: http,
    interval: 86400, # å•ä½ç§’ï¼Œ86400s = 1d
    health-check:
      { enable: true, url: https://www.gstatic.com/generate_204, interval: 600 },
  }

# åœ°åŒºåˆ†ç»„å¼•ç”¨
use-all-proxy: &use-all-proxy
  type: url-test
  interval: 600
  use:
    - www.eevpn.com
    - hiclouda.com
    - æ…ˆå–„æœºåœº.xyz
    - cf.1air.xyz
    - www.ä¸‰æ¯›æœºåœº.shop
    - dash.fscloud.cc
    - bai.ee
    - ä¸€å…ƒæœºåœº.com
    - ä¸€å…ƒè€…ä¹Ÿ.com

use-url-test: &use-url-test
  type: url-test
  interval: 600

######### é”šç‚¹ end #######

# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  ä¸€å…ƒæœºåœº.com:
    <<: *use-health-check
    url: "https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=25f5c0ab285718aa7bb60dc0292ad222"
    path: ./proxy-providers/ä¸€å…ƒæœºåœº.com.yaml

  dash.fscloud.cc:
    <<: *use-health-check
    url: "https://sub.fscloud.cc/api/v1/client/subscribe?token=ade84f590eeaa4b0d33696801995cdf8"
    path: ./proxy-providers/dash.fscloud.cc.yaml

  ä¸€å…ƒè€…ä¹Ÿ.com:
    <<: *use-health-check
    url: "https://dy.v-too.cloud/api/v1/client/subscribe?token=19e23419d0d49cfdb4238ac7fe34367f"
    path: ./proxy-providers/ä¸€å…ƒè€…ä¹Ÿ.com.yaml

  bai.ee:
    <<: *use-health-check
    url: "https://dy.zzjq.xyz/api/v1/client/subscribe?token=236d4c6786b708626c13b3242d29be82"
    path: ./proxy-providers/bai.ee.yaml

  www.eevpn.com:
    <<: *use-health-check
    url: "https://api.ejiasu.net/api/v1/client/subscribe?token=554a1dc8e56be01a10d4d619840c7ed9"
    path: ./proxy-providers/www.eevpn.com.yaml

  hiclouda.com:
    <<: *use-health-check
    url: "https://subscr.b-cdn.net/api/v2/subscr?scrid=7eebd037ae7a4cd9aad2ccd616997a42"
    path: ./proxy-providers/hiclouda.com.yaml

  æ…ˆå–„æœºåœº.xyz:
    <<: *use-health-check
    url: "https://www.csyyds.xyz/api/v1/client/subscribe?token=74f3463174d4a4fdf355f42c9e6cb493"
    path: ./proxy-providers/æ…ˆå–„æœºåœº.xyz.yaml

  www.ä¸‰æ¯›æœºåœº.shop:
    <<: *use-health-check
    url: "https://dy.jimaoyun.top/api/v1/client/subscribe?token=e768edb08411c217faf4e1a18ac6654e"
    path: ./proxy-providers/www.ä¸‰æ¯›æœºåœº.shop.yaml

  cf.1air.xyz:
    <<: *use-health-check
    url: "https://1air.393636.xyz/api/v1/client/subscribe?token=244ec3582cea80099539db6f87aaafdf&flag=clash"
    path: ./proxy-providers/cf.1air.xyz.yaml

rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: yaml
    path: ./rule-providers/LocalAreaNetwork.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    interval: 86400 # å•ä½ç§’ï¼Œ86400s = 1d

# ==================== é…ç½®å¼€å§‹ ======================
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
tun:
  stack: system
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
# ==================== é…ç½®ç»“æŸ ======================

proxies:

proxy-groups:
  - {
      name: é»˜è®¤,
      type: select,
      proxies:
        [
          è‡ªåŠ¨é€‰æ‹©,
          è´Ÿè½½å‡è¡¡,
          æ•…éšœè½¬ç§»,
          æ‰‹åŠ¨é€‰æ‹©,
          é€‰æ‹©æœºåœº,
          é¦™æ¸¯,
          å°æ¹¾,
          æ—¥æœ¬,
          æ–°åŠ å¡,
          ç¾å›½,
          å…¶å®ƒåœ°åŒº,
          DIRECT,
        ],
    }
  - { name: è‡ªåŠ¨é€‰æ‹©, <<: *use-all-proxy, tolerance: 10 }
  - { name: æ‰‹åŠ¨é€‰æ‹©, <<: *use-all-proxy, type: select }
  - {
      name: æ‰‹åŠ¨é€‰æ‹©2,
      type: select,
      proxies:
        [
          é»˜è®¤,
          é¦™æ¸¯,
          å°æ¹¾,
          æ—¥æœ¬,
          æ–°åŠ å¡,
          ç¾å›½,
          å…¶å®ƒåœ°åŒº,
          æ‰‹åŠ¨é€‰æ‹©,
          è‡ªåŠ¨é€‰æ‹©,
          è´Ÿè½½å‡è¡¡,
          æ•…éšœè½¬ç§»,
          DIRECT,
        ],
    }
  - {
      name: é€‰æ‹©æœºåœº,
      type: select,
      proxies:
        [
          www.eevpn.com,
          hiclouda.com,
          æ…ˆå–„æœºåœº.xyz,
          cf.1air.xyz,
          www.ä¸‰æ¯›æœºåœº.shop,  
          dash.fscloud.cc,
          bai.ee,
          ä¸€å…ƒæœºåœº.com,
          ä¸€å…ƒè€…ä¹Ÿ.com,
        ],
    }
  - {
      name: è´Ÿè½½å‡è¡¡,
      <<: *use-all-proxy,
      type: load-balance,
      strategy: consistent-hashing,
    }
  - { name: æ•…éšœè½¬ç§», <<: *use-all-proxy, type: fallback }

  - { name: Abroad SSH, <<: *use-pg }
  - { name: Google, <<: *use-pg }
  - { name: Scholar, <<: *use-pg }
  - { name: GitHub, <<: *use-pg }

  - { name: Apple, <<: *use-pg-cn }

  - { name: OpenAI, <<: *use-pg }
  - { name: NETFLIX, <<: *use-pg }

  - { name: å›½å†…, <<: *use-pg-cn }
  - { name: æ¼ç½‘ä¹‹é±¼, <<: *use-pg }

  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - { name: é¦™æ¸¯, <<: *use-all-proxy, filter: "(?i)æ¸¯|hk|hongkong|hong kong" }
  - { name: å°æ¹¾, <<: *use-all-proxy, filter: "(?i)å°|tw|taiwan" }
  - { name: æ—¥æœ¬, <<: *use-all-proxy, filter: "(?i)æ—¥æœ¬|jp|japan" }
  - {
      name: ç¾å›½,
      <<: *use-all-proxy,
      filter: "(?i)ç¾|us|unitedstates|united states",
    }
  - { name: æ–°åŠ å¡, <<: *use-all-proxy, filter: "(?i)(æ–°|sg|singapore)" }
  - {
      name: å…¶å®ƒåœ°åŒº,
      <<: *use-all-proxy,
      filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*",
    }

  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - { name: www.eevpn.com, <<: *use-url-test, use: [www.eevpn.com] }
  - { name: hiclouda.com, <<: *use-url-test, use: [hiclouda.com] }
  - { name: æ…ˆå–„æœºåœº.xyz, <<: *use-url-test, use: [æ…ˆå–„æœºåœº.xyz] }
  - { name: cf.1air.xyz, <<: *use-url-test, use: [cf.1air.xyz] }
  - { name: www.ä¸‰æ¯›æœºåœº.shop, <<: *use-url-test, use: [www.ä¸‰æ¯›æœºåœº.shop] }
  - { name: dash.fscloud.cc, <<: *use-url-test, use: [dash.fscloud.cc] }
  - { name: bai.ee, <<: *use-url-test, use: [bai.ee] }
  - { name: ä¸€å…ƒæœºåœº.com, <<: *use-url-test, use: [ä¸€å…ƒæœºåœº.com] }
  - { name: ä¸€å…ƒè€…ä¹Ÿ.com, <<: *use-url-test, use: [ä¸€å…ƒè€…ä¹Ÿ.com] }

rules:
  - RULE-SET,LocalAreaNetwork,DIRECT

  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(GEOSITE,geolocation-!cn),REJECT # quic

  - AND,((DOMAIN-SUFFIX,github.com),(DST-PORT,22)),Abroad SSH
  - GEOSITE,openai,OpenAI
  - GEOSITE,github,GitHub
  - GEOSITE,apple,Apple
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,category-scholar-!cn,Scholar
  - GEOSITE,geolocation-!cn,æ¼ç½‘ä¹‹é±¼
  - GEOSITE,google@cn,å›½å†…
  - GEOSITE,google,Google

  - GEOSITE,CN,å›½å†…
  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,CN,å›½å†…
  - DST-PORT,22,Abroad SSH
  - MATCH,æ¼ç½‘ä¹‹é±¼
