# https://wiki.metacubex.one/example/#meta

######### é”šç‚¹ start #######
# proxy ç›¸å…³
use-pg:
  &use-pg {
    type: select,
    proxies:
      [
        é»˜è®¤,
        é¦™æ¸¯,
        å°æ¹¾,
        æ—¥æœ¬,
        æ–°åŠ å¡,
        ç¾å›½,
        å…¶å®ƒåœ°åŒº,
        æ‰‹åŠ¨é€‰æ‹©,
        è‡ªåŠ¨é€‰æ‹©,
        è´Ÿè½½å‡è¡¡,
        æ•…éšœè½¬ç§»,
        DIRECT,
      ],
  }

# proxy ç›¸å…³ cn
use-pg-cn:
  &use-pg-cn {
    type: select,
    proxies:
      [
        DIRECT,
        é»˜è®¤,
        é¦™æ¸¯,
        å°æ¹¾,
        æ—¥æœ¬,
        æ–°åŠ å¡,
        ç¾å›½,
        å…¶å®ƒåœ°åŒº,
        æ‰‹åŠ¨é€‰æ‹©,
        è‡ªåŠ¨é€‰æ‹©,
        è´Ÿè½½å‡è¡¡,
        æ•…éšœè½¬ç§»,
      ],
  }

#è¿™é‡Œæ˜¯è®¢é˜…æ›´æ–°å’Œå»¶è¿Ÿæµ‹è¯•ç›¸å…³çš„
use-health-check:
  &use-health-check {
    type: http,
    interval: 86400,
    health-check:
      {
        enable: true,
        url: https://www.gstatic.com/generate_204,
        interval: 300,
      },
  }

# åœ°åŒºåˆ†ç»„å¼•ç”¨
use-all-proxy: &use-all-proxy
  type: url-test
  interval: 300
  use:
    - ä¸€å…ƒæœºåœº.com
    - dash.fscloud.cc
    - ä¸€å…ƒè€…ä¹Ÿ.com
    - bai.ee
    - www.eevpn.com
    - hiclouda.com
    - æ…ˆå–„æœºåœº.xyz
    - www.ä¸‰æ¯›æœºåœº.shop
    - cf.1air.xyz

use-dns: &use-dns
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

######### é”šç‚¹ end #######

# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  ä¸€å…ƒæœºåœº.com:
    <<: *use-health-check
    url: "https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=25f5c0ab285718aa7bb60dc0292ad222"
    path: ./proxy_providers/ä¸€å…ƒæœºåœº.com.yaml

  dash.fscloud.cc:
    <<: *use-health-check
    url: "https://sub.fscloud.cc/api/v1/client/subscribe?token=ade84f590eeaa4b0d33696801995cdf8"
    path: ./proxy_providers/dash.fscloud.cc.yaml

  ä¸€å…ƒè€…ä¹Ÿ.com:
    <<: *use-health-check
    url: "https://dy.v-too.cloud/api/v1/client/subscribe?token=19e23419d0d49cfdb4238ac7fe34367f"
    path: ./proxy_providers/ä¸€å…ƒè€…ä¹Ÿ.com.yaml

  bai.ee:
    <<: *use-health-check
    url: "https://dy.zzjq.xyz/api/v1/client/subscribe?token=236d4c6786b708626c13b3242d29be82"
    path: ./proxy_providers/bai.ee.yaml

  www.eevpn.com:
    <<: *use-health-check
    url: "https://api.ejiasu.net/api/v1/client/subscribe?token=554a1dc8e56be01a10d4d619840c7ed9"
    path: ./proxy_providers/www.eevpn.com.yaml

  hiclouda.com:
    <<: *use-health-check
    url: "https://subscr.b-cdn.net/api/v2/subscr?scrid=7eebd037ae7a4cd9aad2ccd616997a42"
    path: ./proxy_providers/hiclouda.com.yaml

  æ…ˆå–„æœºåœº.xyz:
    <<: *use-health-check
    url: "https://www.csyyds.xyz/api/v1/client/subscribe?token=74f3463174d4a4fdf355f42c9e6cb493"
    path: ./proxy_providers/æ…ˆå–„æœºåœº.xyz.yaml

  www.ä¸‰æ¯›æœºåœº.shop:
    <<: *use-health-check
    url: "https://dy.jimaoyun.top/api/v1/client/subscribe?token=e768edb08411c217faf4e1a18ac6654e"
    path: ./proxy_providers/www.ä¸‰æ¯›æœºåœº.shop.yaml

  cf.1air.xyz:
    <<: *use-health-check
    url: "https://1air.393636.xyz/api/v1/client/subscribe?token=244ec3582cea80099539db6f87aaafdf&flag=clash"
    path: ./proxy_providers/cf.1air.xyz.yaml

mode: rule
ipv6: true
log-level: info
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

# tun:
#   enable: true
#   stack: gvisor #system
#   dns-hijack:
#     - "any:53"
#   auto-route: true
#   auto-detect-interface: true

dns:
  <<: *use-dns
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip # redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - apps.apple.com

  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4#dns
    - tls://1.1.1.1#dns
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"

proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: engage.cloudflareclient.com
  #   port: 2408
  #   ip: "172.16.0.2/32"
  #   ipv6: "2606::1/128"        # è‡ªè¡Œæ›¿æ¢
  #   private-key: "private-key" # è‡ªè¡Œæ›¿æ¢
  #   public-key: "public-key"   # è‡ªè¡Œæ›¿æ¢
  #   udp: true
  #   reserved: "abba"           # è‡ªè¡Œæ›¿æ¢
  #   mtu: 1280
  #   dialer-proxy: "dns"
  #   remote-dns-resolve: true
  #   dns:
  #     - https://dns.cloudflare.com/dns-query

proxy-groups:
  - {
      name: é»˜è®¤,
      type: select,
      proxies:
        [
          è‡ªåŠ¨é€‰æ‹©,
          è´Ÿè½½å‡è¡¡,
          æ•…éšœè½¬ç§»,
          æ‰‹åŠ¨é€‰æ‹©,
          é¦™æ¸¯,
          å°æ¹¾,
          æ—¥æœ¬,
          æ–°åŠ å¡,
          ç¾å›½,
          å…¶å®ƒåœ°åŒº,
          DIRECT,
        ],
    }

  - { name: è‡ªåŠ¨é€‰æ‹©, <<: *use-all-proxy, tolerance: 2 }

  - { name: æ‰‹åŠ¨é€‰æ‹©, <<: *use-all-proxy, type: select }

  - {
      name: è´Ÿè½½å‡è¡¡,
      <<: *use-all-proxy,
      type: load-balance,
      strategy: consistent-hashing,
    }

  - { name: æ•…éšœè½¬ç§», <<: *use-all-proxy, type: fallback }

  # - {name: dns, type: select, proxies: [DIRECT, WARP, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, å…¶å®ƒåœ°åŒº, æ‰‹åŠ¨é€‰æ‹©, è‡ªåŠ¨é€‰æ‹©]}  # åŠ å…¥ WARP
  - { name: dns, <<: *use-pg-cn }

  - { name: Google, <<: *use-pg }
  - { name: OpenAI, <<: *use-pg }
  - { name: Google Scholar, <<: *use-pg }
  - { name: GitHub, <<: *use-pg }
  - { name: Docker, <<: *use-pg }

  - { name: Microsoft, <<: *use-pg }
  - { name: Telegram, <<: *use-pg }
  - { name: Twitter, <<: *use-pg }
  - { name: Apple, <<: *use-pg-cn }

  - { name: ehentai, <<: *use-pg }
  - { name: å“”å“©å“”å“©, <<: *use-pg-cn }
  - { name: å“”å“©ä¸œå—äºš, <<: *use-pg }
  - { name: å·´å“ˆå§†ç‰¹, <<: *use-pg }
  - { name: YouTube, <<: *use-pg }
  - { name: NETFLIX, <<: *use-pg }
  - { name: Spotify, <<: *use-pg }

  - { name: å›½å†…, <<: *use-pg-cn }
  - { name: æ¼ç½‘ä¹‹é±¼, <<: *use-pg }

  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - { name: é¦™æ¸¯, <<: *use-all-proxy, filter: "(?i)æ¸¯|hk|hongkong|hong kong" }
  - { name: å°æ¹¾, <<: *use-all-proxy, filter: "(?i)å°|tw|taiwan" }
  - { name: æ—¥æœ¬, <<: *use-all-proxy, filter: "(?i)æ—¥æœ¬|jp|japan" }
  - {
      name: ç¾å›½,
      <<: *use-all-proxy,
      filter: "(?i)ç¾|us|unitedstates|united states",
    }
  - { name: æ–°åŠ å¡, <<: *use-all-proxy, filter: "(?i)(æ–°|sg|singapore)" }
  - {
      name: å…¶å®ƒåœ°åŒº,
      <<: *use-all-proxy,
      filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*",
    }

rules:
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(GEOSITE,geolocation-!cn),REJECT # quic
  - GEOSITE,biliintl,å“”å“©ä¸œå—äºš
  - GEOSITE,openai,OpenAI
  - GEOSITE,ehentai,ehentai
  - GEOSITE,github,GitHub
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,apple,Apple
  - GEOSITE,google-scholar,Google Scholar
  - GEOSITE,docker,Docker
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,telegram,Telegram
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,bilibili,å“”å“©å“”å“©
  - GEOSITE,bahamut,å·´å“ˆå§†ç‰¹
  - GEOSITE,spotify,Spotify
  - GEOSITE,geolocation-!cn,æ¼ç½‘ä¹‹é±¼

  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,telegram,Telegram
  - GEOIP,twitter,Twitter
  - GEOSITE,CN,å›½å†…
  - GEOIP,CN,å›½å†…
  - MATCH,æ¼ç½‘ä¹‹é±¼
