version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

clash_rule_base = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/config/base/clash.yml"


[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ”¯ æ•…éšœè½¬ç§»", "[]ğŸ”® è´Ÿè½½å‡è¡¡", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*"]
[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ”¯ æ•…éšœè½¬ç§»"
type = "fallback"
rule = [".*"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ”® è´Ÿè½½å‡è¡¡"
type = "load-balance"
rule = [".*"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§†é¢‘"
type = "select"
rule = ["[]ğŸ¥ å¥ˆé£èŠ‚ç‚¹", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸ¤– OpenAi"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸ è°·æ­Œç¿»è¯‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸš§ GitHub ssh git"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸš§ GitHub web"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸš§ ä¾èµ–ä»“åº“"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "â“‚ï¸ Google"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT"]
[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©"]
[[custom_groups]]
name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]
[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ¸¯|HK|Hong Kong)"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.google.com/generate_204"
interval = 300
tolerance = 50
[[custom_groups]]
name = "ğŸ¥ å¥ˆé£èŠ‚ç‚¹"
type = "select"
rule = ["(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media)"]



[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
[[rulesets]]
group = "â“‚ï¸ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"
[[rulesets]]
group = "ğŸ¤– OpenAi"
ruleset = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/OpenAi.list"
[[rulesets]]
group = "ğŸ è°·æ­Œç¿»è¯‘"
ruleset = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/TranslateGoogle.list"
[[rulesets]]
group = "ğŸš§ GitHub web"
ruleset = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/Github.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/GithubMirror.list"
[[rulesets]]
group = "ğŸš§ ä¾èµ–ä»“åº“"
ruleset = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/CodeDep.list"
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/DevSourceSite.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"
[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"